import { LeaderboardUser } from "./types";

export const leaderboardMock: LeaderboardUser[] = [
  {
    id: "1",
    rank: 1,
    name: "Sarah Johnson",
    storeName: "SJ Fashion Hub",
    sales: 342,
    earnings: 4200,
    conversionRate: 4.8,
    rating: 4.9,
    clicks: 7100,
    orders: 342,
    commissionRate: 12,
    topProduct: "Summer Dress",
    joinedAt: "2024-02-10",
  },
  {
    id: "2",
    rank: 2,
    name: "Michael Chen",
    storeName: "Tech Trends",
    sales: 298,
    earnings: 3650,
    conversionRate: 4.2,
    rating: 4.7,
    clicks: 6800,
    orders: 298,
    commissionRate: 10,
    topProduct: "Wireless Earbuds",
    joinedAt: "2024-03-01",
  },
  {
    id: "3",
    rank: 3,
    name: "Emily Rodriguez",
    storeName: "Home Essentials",
    sales: 275,
    earnings: 3300,
    conversionRate: 3.9,
    rating: 4.8,
    clicks: 6400,
    orders: 275,
    commissionRate: 11,
    topProduct: "Kitchen Organizer",
    joinedAt: "2024-01-22",
  },
];
